sonar.organization=ksurahan-source
sonar.projectKey=ksurahan-source_hiob-data
sonar.projectName=hiob-data
sonar.sourceEncoding=UTF-8

sonar.sources=hiob_data
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
